# Generated by Django 5.1.3 on 2024-11-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
    ]
