# Generated by Django 5.1.3 on 2024-11-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0002_resume_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="education",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="resume",
            name="skills",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="resume",
            name="work_experience",
            field=models.TextField(blank=True, default=""),
        ),
    ]
