# Generated by Django 5.1.3 on 2024-11-29 23:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0007_remove_resume_education_remove_resume_personal_info_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resume",
            old_name="work_experience",
            new_name="resume_content",
        ),
    ]
